<?php
$pageTitle = 'Pakistan Sourcing Partner | Sialkot, Wazirabad & Faisalabad';
$pageDesc = 'Source instruments, sports goods, cutlery, apparel and textiles from Pakistan. SialSourcing coordinates supplier selection, samples, quality checks and shipping.';
$canonicalPath = '/';
require_once __DIR__ . '/includes/header.php';
$categories = [
 ['01','Dental & surgical instruments','Forceps, scissors, dental hand instruments and instrument sets.','dental-instruments','Sialkot'],
 ['02','Sports goods & soccer balls','Custom balls, training equipment and branded sports goods.','custom-soccer-balls','Sialkot'],
 ['03','Activewear & team uniforms','Performance fabrics, sublimation, sizing and private labels.','activewear-sports-uniforms','Sialkot'],
 ['04','Cutlery & kitchenware','Stainless steel flatware, kitchen knives and hospitality sets.','cutlery','Wazirabad'],
 ['05','Textiles & home linens','Towels, bed linen, woven fabrics and made-up textiles.','home-textiles','Faisalabad'],
 ['06','Leather goods & workwear','Gloves, leather accessories, scrubs and uniforms.','leather-goods','Sialkot'],
];
?>
<section class="source-hero">
  <div class="source-hero-copy">
    <p class="eyebrow">Your sourcing partner in Pakistan</p>
    <h1>Closer to the source.<br><em>Clearer at every step.</em></h1>
    <p class="hero-intro">Find the right manufacturing partner in Sialkot, Wazirabad or Faisalabad. From your first specification to samples, quality checks and shipment, bring the details together with SialSourcing.</p>
    <div class="button-row"><a class="btn btn-gold" href="/contact">Discuss your sourcing brief <?= icon('arrow-right',18) ?></a><a class="text-link light" href="/products">Explore products</a></div>
    <div class="hero-facts"><span>Supplier matching</span><span>Sample coordination</span><span>Quality oversight</span></div>
  </div>
  <figure class="source-hero-image"><img src="/assets/images/sourcing-materials.jpg" alt="Illustrative arrangement of textiles, leather and metal instruments" width="1122" height="1402" fetchpriority="high"><figcaption>Materials. Craft. Possibility. <span>Illustrative composition</span></figcaption></figure>
</section>
<div class="region-strip"><span>Three manufacturing regions.<br><strong>One point of coordination.</strong></span><a href="/sialkot-sourcing">Sialkot <small>Instruments · Sports · Leather</small></a><a href="/wazirabad-sourcing">Wazirabad <small>Cutlery · Kitchenware</small></a><a href="/faisalabad-sourcing">Faisalabad <small>Textiles · Apparel · Home linens</small></a></div>
<section class="editorial-section" id="products"><div class="section-heading"><div><p class="eyebrow">Made for your market</p><h2>What would you<br>like to source?</h2></div><p>Start with the product. We help turn your requirements into a supplier brief, an agreed sample and a practical production plan.</p></div>
<div class="category-grid"><?php foreach($categories as [$number,$title,$desc,$slug,$region]): ?><a href="/<?= e($slug) ?>" class="category-card"><div class="card-top"><span><?= e($number) ?></span><span><?= e($region) ?></span></div><h3><?= e($title) ?></h3><p><?= e($desc) ?></p><span class="card-action">Explore sourcing <?= icon('arrow-right',18) ?></span></a><?php endforeach; ?></div><a class="text-link" href="/products">View all product categories <?= icon('arrow-right',18) ?></a></section>
<section class="process-section" id="how-it-works"><div><p class="eyebrow">From brief to shipment</p><h2>A clear process.<br>A considered result.</h2><p>Keep specifications, commercial terms and quality expectations aligned before production begins.</p><a class="text-link light" href="/solutions">How we work <?= icon('arrow-right',18) ?></a></div><ol class="process-list"><li><span>01</span><div><h3>Define the requirement</h3><p>Share the product, quantity, destination, target dates and any drawings or reference samples.</p></div></li><li><span>02</span><div><h3>Compare the right capabilities</h3><p>Review a supplier shortlist against materials, processes, capacity and the documentation your market needs.</p></div></li><li><span>03</span><div><h3>Approve the details</h3><p>Agree samples, tolerances, packaging, inspection criteria and commercial terms before committing to production.</p></div></li><li><span>04</span><div><h3>Follow production through</h3><p>Coordinate progress checks, inspection records, export documents and the agreed shipping arrangements.</p></div></li></ol></section>
<section class="editorial-section assurance-section"><div><p class="eyebrow">Confidence comes from evidence</p><h2>Know what you are<br>approving.</h2><p>A good sourcing decision depends on more than a factory name or a badge. Ask for evidence that relates to your product, its manufacturer and your destination market.</p><a class="btn btn-dark" href="/lab-qc">Explore quality control <?= icon('arrow-right',18) ?></a></div><div class="evidence-list"><article><span>01 / Product</span><h3>A specification you can check</h3><p>Materials, dimensions, finish, performance and packaging recorded against an approved sample.</p></article><article><span>02 / Manufacturer</span><h3>Documentation with a clear scope</h3><p>Check who issued a certificate, which site and products it covers, and whether it is still valid.</p></article><article><span>03 / Shipment</span><h3>Inspection before the next decision</h3><p>Agree an inspection plan and review the findings before shipment release under your contract.</p></article></div></section>
<section class="resource-band"><div><p class="eyebrow">A better brief gets a better answer</p><h2>Bring your next project into focus.</h2><p>Use the sourcing brief, apparel tech pack and sample inspection report to prepare your requirements.</p></div><a href="/resources" class="btn btn-dark">Buyer resources <?= icon('arrow-right',18) ?></a></section>
<section class="editorial-section home-faq"><div><p class="eyebrow">Before we begin</p><h2>Your first questions,<br>answered.</h2></div><div><details><summary>Are you a manufacturer or a sourcing company?</summary><p>SialSourcing is a sourcing and supply chain partner. We coordinate with manufacturers and help buyers define requirements, evaluate options and follow their orders through.</p></details><details><summary>Can you source products from all three regions?</summary><p>Send your brief for instruments, sports goods and leather from Sialkot; cutlery from Wazirabad; or textiles from Faisalabad. The team will confirm whether a suitable supplier and production route are available for your request.</p></details><details><summary>What are the minimum order quantity and lead time?</summary><p>They depend on the product, tooling, materials, customisation and factory capacity. Your quotation should state the MOQ, sampling period and production schedule for the specific order.</p></details><details><summary>Can you help with destination-market requirements?</summary><p>Include the destination and intended use in your brief. Relevant manufacturer and product documentation can then be reviewed; approvals and import obligations must be confirmed for that product and market.</p></details></div></section>
<section class="closing-cta"><p class="eyebrow">Let's build your sourcing plan</p><h2>Your next product.<br>Our next conversation.</h2><p>Tell us what you need, where it is going and what matters most.</p><a class="btn btn-gold" href="/contact">Send your sourcing brief <?= icon('arrow-right',18) ?></a></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
