<?php
$pageTitle = 'Products to Source from Pakistan';
$pageDesc = 'Explore dental and surgical instruments, sports goods, apparel, leather, cutlery and textiles from Sialkot, Wazirabad and Faisalabad.';
$canonicalPath = '/products';
require __DIR__ . '/includes/header.php';
$products = db()->query('SELECT * FROM products WHERE is_active=1 ORDER BY sort_order')->fetchAll();
$products = array_values(array_filter($products,fn($p)=>preg_match('/^[a-z0-9-]+$/',$p['slug']) && is_file(__DIR__.'/'.$p['slug'].'.php')));
if (!in_array('home-textiles', array_column($products,'slug'), true)) $products[]=['title'=>'Textiles & Home Linens','slug'=>'home-textiles','description'=>'Prepare a brief for towels, bed linen, woven fabric and other made-up textiles from Faisalabad.'];
$schema=['@context'=>'https://schema.org','@type'=>'CollectionPage','name'=>'Products to source from Pakistan','url'=>$canonicalUrl,'mainEntity'=>['@type'=>'ItemList','itemListElement'=>array_map(fn($p,$i)=>['@type'=>'ListItem','position'=>$i+1,'name'=>$p['title'],'url'=>$canonicalOrigin.'/'.$p['slug']],$products,array_keys($products))]];
?>
<script type="application/ld+json"><?= json_encode($schema, JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
<section class="catalogue-intro"><p class="eyebrow">Explore manufacturing possibilities</p><h1>Find your product.<br>Define your next step.</h1><p>Browse sourcing categories across Sialkot, Wazirabad and Faisalabad. Availability, order quantities and market requirements are confirmed against your specific brief.</p></section>
<section class="editorial-section"><label for="category-search" class="eyebrow" style="display:block">Find a category</label><input id="category-search" class="category-search" type="search" placeholder="Search instruments, textiles, soccer balls…" autocomplete="off" aria-controls="product-categories"><p id="category-count" class="field-note" role="status"><?= count($products) ?> sourcing categories</p>
<div class="category-grid" id="product-categories"><?php foreach($products as $p): ?><a class="category-card" href="/<?= e($p['slug']) ?>" data-category-search="<?= e(strtolower($p['title'].' '.$p['description'])) ?>"><span class="category-label"><?= $p['slug']==='cutlery'?'Wazirabad':($p['slug']==='home-textiles'?'Faisalabad':'Sialkot') ?> · Pakistan</span><h2 style="font-size:1.5rem;margin-bottom:16px"><?= e($p['title']) ?></h2><p><?= e($p['description']) ?></p><span class="card-action">Explore sourcing <?= icon('arrow-right',18) ?></span></a><?php endforeach; ?></div><p id="category-empty" class="empty-state" hidden>No matching category. <a class="text-link" href="/contact">Tell us what you are looking for.</a></p><a class="text-link" href="/sourcing-regions">Explore the manufacturing regions <?= icon('arrow-right',18) ?></a></section>
<section class="closing-cta"><p class="eyebrow">Something else in mind?</p><h2>Start with your brief.</h2><p>Tell us about the product and your requirements. We will confirm whether we can identify a suitable manufacturing route.</p><a class="btn btn-gold" href="/contact">Discuss a product <?= icon('arrow-right',18) ?></a></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
