</main>
<footer class="site-footer"><div class="footer-inner">
<div class="footer-brand"><a class="nav-logo" href="/"><span>Sial<em>Sourcing</em></span></a><p>Your connection to manufacturing in Pakistan. A clear brief, the right capabilities and coordination through shipment.</p><a href="mailto:<?= e(setting('contact_email','info@sialsourcing.com')) ?>"><?= e(setting('contact_email','info@sialsourcing.com')) ?></a></div>
<div class="footer-col"><h2>Explore products</h2><a href="/dental-instruments">Dental instruments</a><a href="/surgical-instruments">Surgical instruments</a><a href="/custom-soccer-balls">Custom soccer balls</a><a href="/activewear-sports-uniforms">Activewear & uniforms</a><a href="/cutlery">Cutlery & kitchenware</a><a href="/home-textiles">Textiles & home linens</a><a href="/products">All categories</a></div>
<div class="footer-col"><h2>Manufacturing regions</h2><a href="/sialkot-sourcing">Sialkot</a><a href="/wazirabad-sourcing">Wazirabad</a><a href="/faisalabad-sourcing">Faisalabad</a><h2 class="footer-subheading">Buyer resources</h2><a href="/resources">Templates & checklists</a><a href="/blog">Sourcing insights</a><a href="/faq">Frequently asked questions</a></div>
<div class="footer-col"><h2>Work with us</h2><a href="/contact">Request a quote</a><a href="/solutions">Sourcing services</a><a href="/lab-qc">Quality control</a><a href="/qc-inspection-request">Request an inspection</a><a href="/for-manufacturers">For manufacturers</a><a href="/about">About SialSourcing</a><a href="/team">Our team</a></div>
</div><div class="footer-bottom"><span>© <?= date('Y') ?> <?= e(setting('site_name','SialSourcing')) ?>. All rights reserved.</span><span>Pakistan sourcing. International perspective.</span></div></footer>
<?php if (preg_replace('/\D/','',setting('contact_phone',''))): ?><a class="wa-float" aria-label="Contact SialSourcing on WhatsApp" href="https://wa.me/<?= e(preg_replace('/\D/','',setting('contact_phone','+92-300-1100110'))) ?>?text=<?= rawurlencode('Hello, I would like to discuss a sourcing brief.') ?>" target="_blank" rel="noopener noreferrer"><?= icon('whatsapp',27) ?></a><?php endif; ?>
<script src="/assets/js/main.js?v=<?= (int) filemtime(__DIR__.'/../assets/js/main.js') ?>" defer></script>
</body></html>
